name: bloglinux
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shimmer: ^3.0.0


flutter_native_splash:
  color: "6558DA"
  image: assets/img/error_loading.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/img/error_loading.png
    icon_background_color: "6558DA"
    image_dark: assets/img/error_loading.png
    icon_background_color_dark: "6558DA"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
