name: bloglinux
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
